<h1>Basisdatenbank</h1>

<p><a href="index.php?pid=intranet_admin_db_personenliste">Personen</a> - Daten zu Mitgliedern, Ehepartnern, Vereinsfreunden, etc. werden als Personendatensätze geführt. Die Datensätze werden diesen verschiedenen Gruppen über die Eigenschaft "Gruppe" zugeordnet.</p>
<p><a href="index.php?pid=intranet_admin_db_semesterliste">Semester</a> - Semesterdatensätze umfassen jeweils Angaben zum Vorstand, Ämtern und Semesterprogrammcover eines Semesters.</p>
<p><a href="index.php?pid=intranet_admin_db_veranstaltungsliste">Veranstaltungen</a> - Veranstaltungen werden unabhängig vom Semester erfasst und vom System automatisch auf Basis ihres Datums dem entsprechenden Semester zugeordnet.</p>
<p><a href="index.php?pid=intranet_admin_db_vereinsliste">Vereine</a> - Vereinsdaten können über die Eigenschaft "Anschreiben zusenden" im Zusammenspiel mit dem Adressdatenexport als Datenbasis für Serienbriefe genutzt werden. Zudem können Personen über die Tabelle "Mitgliedschaften" diese Vereine zugeordnet werden.</p>
<p><a href="index.php?pid=intranet_admin_db_vereinsmitgliedschaftenliste">Mitgliedschaften</a> - Personen, bei denen Mitgliedschaften in weiteren Vereinen gespeichert sind, erhalten hinter ihrem Namen ein entsprechendes Vereinskürzel.</p>
<p><a href="index.php?pid=intranet_admin_db_vipliste">Vips</a> - Datensätze zu Vips werden getrennt von vereinsnahen Personen gespeichert und können über die Exportfunktion als Datenbasis für Serienbriefe genutzt werden.</p>
<p><a href="index.php?pid=intranet_admin_db_gruppen">Gruppen</a> - Gruppen dienen der Einteilung der Personen in Vereinsgruppen wie Füchse und Burschen.</p>
<p><a href="index.php?pid=intranet_admin_db_status">Status</a> - Status dienen der weiteren organisatorischen Einteilung der Personen in Inaktive, A-Philister, B-Philister, ex loco, etc. Sie haben aber keine Auswirkung auf die Zugangskontrolle für Intranetseiten.</p>
<p><a href="index.php?pid=intranet_admin_db_region">Regionen</a> - Jede Person kann zwei Regionen zugeordnet werden. Damit lassen sich Ortszirkel erstellen, die z. B. im Rundbriefmodul adressiert werden können.</p>